// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import { type ComponentProps, splitProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Menu
 * ```
 *       █          █
 *        ██      ██
 *          ██  ██
 *           ████
 *          ██  ██
 *        ██      ██
 *       █          █
 * ```
 */
export const IconCloseMd = (props: IconProps) => {
    const [pickedProps, otherProps] = splitProps(props, ['size']);

    return (
        <svg
            role='img'
            aria-label='Close Md'
            width={pickedProps.size || '1em'}
            height={pickedProps.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            {...otherProps}
        >
            <path
                d='M18 18L12 12M12 12L6 6M12 12L18 6M12 12L6 18'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
