// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
    size?: string;
}

/**
    * Edit
    * ```
    *            ██           
    *            ██           
    *            ██           
    *       ████████████      
    *            ██           
    *            ██           
    *            ██           
    * ```
    */
export const IconAddPlus = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Add Plus'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M6 12H12M12 12H18M12 12V18M12 12V6'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
