[project]
name = "comps"
version = "0.1.0"
description = "Cli tool to generate solidJS components"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
]

[project.scripts]
comps = "comps:cli"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
