// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
    size?: string;
}

/**
* Warning
* ```
    *            ██           
    *            ██           
    *            ██           
    *            ██           
    *            ██           
    * ```
    */
export const IconWarning = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Warning'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M12 6V14M12.0498 18V18.1L11.9502 18.1002V18H12.0498Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
