// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
    size?: string;
}

/**
 * Warning
 * ```
 *           ████          
 *       ██        ██      
 *     ██            ██    
 *    ██              ██   
 *   ██          █     ██  
 *   ██     █  ██      ██  
 *   ██      ██        ██  
 *    ██              ██   
 *     ██            ██    
 *       ██        ██      
 *           ████          
 * ```
 */
export const IconCircleCheck = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Circle Check'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M15 10L11 14L9 12M12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
