// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
    size?: string;
}

/**
 * Arrow
 * ```
 *       ██                
 *      ██████████████     
 *       ██                
 *                 ██      
 *      ██████████████     
 *                 ██      
 * ```
 */
export const IconArrowLeftRight = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Arrow Left Right'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M16 13L19 16M19 16L16 19M19 16H5M8 11L5 8M5 8L8 5M5 8H19'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
