// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
    size?: string;
}

/**
 * Arrow
 * ```
 *              ██         
 *              ██         
 *              ██████     
 *      ██████             
 *          ██             
 *          ██             
 * ```
 */
export const IconShrink = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Shrink'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            ref={props.ref}
            {...props}
        >
            <path
                d='M5 14H10V19M19 10H14V5'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
