// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
    size?: string;
}

/**
    * Arrow
    * ```
    *           ████          
    *       ██        ██      
    *     ██            ██    
    *    ██      ██      ██   
    *   ██     ██████     ██  
    *   ██       ██       ██  
    *   ██       ██       ██  
    *    ██      ██      ██   
    *     ██            ██    
    *       ██        ██      
    *           ████          
    * ```
    */
export const IconArrowCircleUp = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Arrow Circle Up'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M15 11L12 8M12 8L9 11M12 8V16M21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21C16.9706 21 21 16.9706 21 12Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
