// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { ComponentProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Arrow
 * ```
 *         █      █
 *          ██  ██
 *            ██
 * ```
 */
export const IconCaretDownMd = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Caret Down Md'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            ref={props.ref}
            {...props}
        >
            <path
                d='M16 10L12 14L8 10'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
