// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { ComponentProps } from 'solid-js';

interface IconProps extends ComponentProps<'svg'> {
    size?: string;
}

/**
 * Interface
 * ```
 *          ██
 *    ████████   ███████
 *                ██
 *    ██████████████   █
 *                ██
 *    ████   ███████████
 *      ██
 * ```
 */
export const IconSlider03 = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Slider03'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            ref={props.ref}
            {...props}
        >
            <path
                d='M10 18H21M3 18H6M6 18V20M6 18V16M20 12H21M3 12H16M16 12V14M16 12V10M14 6H21M3 6H10M10 6V8M10 6V4'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
