// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

interface IconProps extends JSX.SvgSVGAttributes<SVGSVGElement> {
    size?: string;
}

/**
* Interface
* ```
    *         ████████        
    *      ██          ██     
    *     ██            ██    
    *    ██    ██  ██    ██   
    *    ██   ██    ██   ██   
    *    ██    ██  ██    ██   
    *     ██            ██    
    *      ██          ██     
    *         ████████        
    * ```
    */
export const IconRadioFill = (props: IconProps) => {
    return (
        <svg
            role='img'
            aria-label='Radio Fill'
            width={props.size || '1em'}
            height={props.size || '1em'}
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M12 4C7.58172 4 4 7.58172 4 12C4 16.4183 7.58172 20 12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
            <path
                d='M12 9C10.3431 9 9 10.3431 9 12C9 13.6569 10.3431 15 12 15C13.6569 15 15 13.6569 15 12C15 10.3431 13.6569 9 12 9Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
