// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconEditPencilLine01 = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Edit Pencil Line01'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M2 10.0001H10M2 10.0001V8.00006L6 4.00006M2 10.0001L4 10L7.99999 6.00005M6 4.00006L7.43431 2.56573L7.43518 2.56488C7.63262 2.36744 7.73151 2.26854 7.84552 2.2315C7.94594 2.19887 8.05412 2.19887 8.15454 2.2315C8.26846 2.26852 8.36724 2.3673 8.5644 2.56446L9.4343 3.43436C9.63231 3.63237 9.73136 3.73142 9.76846 3.84558C9.80108 3.946 9.80107 4.05418 9.76844 4.1546C9.73138 4.26868 9.63248 4.36758 9.43475 4.56531L9.43431 4.56573L7.99999 6.00005M6 4.00006L7.99999 6.00005'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
