// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconCloseMd = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Close Md'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M18 18L12 12M12 12L6 6M12 12L18 6M12 12L6 18'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
