// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconDragHorizontal = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Drag Horizontal'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M9 7C8.72386 7 8.5 7.22386 8.5 7.5C8.5 7.77614 8.72386 8 9 8C9.27614 8 9.5 7.77614 9.5 7.5C9.5 7.22386 9.27614 7 9 7Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
            <path
                d='M6 7C5.72386 7 5.5 7.22386 5.5 7.5C5.5 7.77614 5.72386 8 6 8C6.27614 8 6.5 7.77614 6.5 7.5C6.5 7.22386 6.27614 7 6 7Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
            <path
                d='M3 7C2.72386 7 2.5 7.22386 2.5 7.5C2.5 7.77614 2.72386 8 3 8C3.27614 8 3.5 7.77614 3.5 7.5C3.5 7.22386 3.27614 7 3 7Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
            <path
                d='M9 4C8.72386 4 8.5 4.22386 8.5 4.5C8.5 4.77614 8.72386 5 9 5C9.27614 5 9.5 4.77614 9.5 4.5C9.5 4.22386 9.27614 4 9 4Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
            <path
                d='M6 4C5.72386 4 5.5 4.22386 5.5 4.5C5.5 4.77614 5.72386 5 6 5C6.27614 5 6.5 4.77614 6.5 4.5C6.5 4.22386 6.27614 4 6 4Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
            <path
                d='M3 4C2.72386 4 2.5 4.22386 2.5 4.5C2.5 4.77614 2.72386 5 3 5C3.27614 5 3.5 4.77614 3.5 4.5C3.5 4.22386 3.27614 4 3 4Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
