// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconUnfoldMore = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Unfold More'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M8 7.5L6 9.5L4 7.5M4 4.5L6 2.5L8 4.5'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
