// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconPlay = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Play'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M2.5 8.66683V3.33349C2.5 2.89371 2.5 2.67357 2.59255 2.54345C2.67332 2.42989 2.79782 2.35532 2.93604 2.33749C3.09434 2.31708 3.2885 2.42063 3.67627 2.62744L8.67627 5.2941L8.67808 5.29491C9.10661 5.52346 9.32098 5.63779 9.39129 5.79016C9.45263 5.92309 9.45263 6.07654 9.39129 6.20947C9.32088 6.36206 9.10601 6.47686 8.67627 6.70605L3.67627 9.37272C3.28823 9.57967 3.0944 9.68283 2.93604 9.6624C2.79782 9.64458 2.67332 9.57003 2.59255 9.45646C2.5 9.32634 2.5 9.10661 2.5 8.66683Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
