// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconTriangleWarning = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Triangle Warning'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M6 4.50003V6.50003M2.18945 7.59993C1.73474 8.38752 1.50744 8.78147 1.54141 9.10461C1.57103 9.38646 1.71896 9.64253 1.94824 9.80911C2.21102 10 2.66545 10 3.57427 10H8.42573C9.33455 10 9.78891 10 10.0517 9.80911C10.281 9.64253 10.429 9.38646 10.4586 9.10461C10.4926 8.78147 10.2653 8.38752 9.81061 7.59993L7.38574 3.39993C6.93103 2.61234 6.70357 2.21861 6.40674 2.08645C6.14783 1.97118 5.852 1.97118 5.5931 2.08645C5.29639 2.21856 5.06907 2.61229 4.61473 3.39922L2.18945 7.59993ZM6.02539 8.00003V8.05003L5.9751 8.05013V8.00003H6.02539Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
