// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconUnfoldLess = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Unfold Less'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M4 9.5L6 7.5L8 9.5M8 2.5L6 4.5L4 2.5'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
