// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconCheckboxUnchecked = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Checkbox Unchecked'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M2 3.6001V8.4001C2 8.96015 2 9.24003 2.10899 9.45394C2.20487 9.6421 2.35774 9.79524 2.5459 9.89111C2.7596 10 3.0395 10 3.59846 10H8.40155C8.9605 10 9.23999 10 9.4537 9.89111C9.64186 9.79524 9.79524 9.6421 9.89111 9.45394C10 9.24024 10 8.96075 10 8.40179V3.59846C10 3.0395 10 2.7596 9.89111 2.5459C9.79524 2.35774 9.64186 2.20487 9.4537 2.10899C9.23979 2 8.96015 2 8.4001 2H3.6001C3.04005 2 2.75981 2 2.5459 2.10899C2.35774 2.20487 2.20487 2.35774 2.10899 2.5459C2 2.75981 2 3.04005 2 3.6001Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
