// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconSwitchLeft = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Switch Left'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M4 9H8C9.65685 9 11 7.65685 11 6C11 4.34315 9.65685 3 8 3H4C2.34315 3 1 4.34315 1 6C1 7.65685 2.34315 9 4 9Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
            <path
                d='M4 4.5C3.17157 4.5 2.5 5.17157 2.5 6C2.5 6.82843 3.17157 7.5 4 7.5C4.82843 7.5 5.5 6.82843 5.5 6C5.5 5.17157 4.82843 4.5 4 4.5Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
