// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconHamburgerMd = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Hamburger Md'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M2.5 8.5H9.5M2.5 6H9.5M2.5 3.5H9.5'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
