// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconExternalLink = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='External Link'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M5.0001 2.5H4.1001C3.54005 2.5 3.25981 2.5 3.0459 2.60899C2.85774 2.70487 2.70487 2.85774 2.60899 3.0459C2.5 3.25981 2.5 3.54005 2.5 4.1001V7.9001C2.5 8.46015 2.5 8.74003 2.60899 8.95394C2.70487 9.1421 2.85774 9.29524 3.0459 9.39111C3.2596 9.5 3.5395 9.5 4.09845 9.5H7.90155C8.4605 9.5 8.74 9.5 8.9537 9.39111C9.14186 9.29524 9.29524 9.14196 9.39111 8.95379C9.5 8.74009 9.5 8.4605 9.5 7.90155V7M10 4.5V2M10 2H7.5M10 2L6.5 5.5'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
