// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconArrowLeftRight = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Arrow Left Right'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M16 13L19 16M19 16L16 19M19 16H5M8 11L5 8M5 8L8 5M5 8H19'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
