// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconCheckboxCheck = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Checkbox Check'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M4 6L5.5 7.5L8 4.5M2 8.4001V3.6001C2 3.04005 2 2.75981 2.10899 2.5459C2.20487 2.35774 2.35774 2.20487 2.5459 2.10899C2.75981 2 3.04005 2 3.6001 2H8.4001C8.96015 2 9.23979 2 9.4537 2.10899C9.64186 2.20487 9.79524 2.35774 9.89111 2.5459C10 2.7596 10 3.0395 10 3.59846V8.40179C10 8.96075 10 9.24024 9.89111 9.45394C9.79524 9.6421 9.64186 9.79524 9.4537 9.89111C9.23999 10 8.9605 10 8.40155 10H3.59846C3.0395 10 2.7596 10 2.5459 9.89111C2.35774 9.79524 2.20487 9.6421 2.10899 9.45394C2 9.24003 2 8.96015 2 8.4001Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
