// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconWarning = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Warning'
            width='24'
            height='24'
            viewBox='0 0 24 24'
            fill='none'
            {...props}
        >
            <path
                d='M12 6V14M12.0498 18V18.1L11.9502 18.1002V18H12.0498Z'
                stroke='currentColor'
                stroke-width='2'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
