// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconSlider02 = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Slider02'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M7 9H10.5M1.5 9H2.5M2.5 9C2.5 9.69036 3.05964 10.25 3.75 10.25C4.44036 10.25 5 9.69036 5 9C5 8.30964 4.44036 7.75 3.75 7.75C3.05964 7.75 2.5 8.30964 2.5 9ZM10 6H10.5M1.5 6H5M6.5 3H10.5M6.5 3C6.5 2.30964 5.94036 1.75 5.25 1.75C4.55964 1.75 4 2.30964 4 3C4 3.69036 4.55964 4.25 5.25 4.25C5.94036 4.25 6.5 3.69036 6.5 3ZM1.5 3H2M8.25 7.25C7.55964 7.25 7 6.69036 7 6C7 5.30964 7.55964 4.75 8.25 4.75C8.94036 4.75 9.5 5.30964 9.5 6C9.5 6.69036 8.94036 7.25 8.25 7.25Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
