// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconPause = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Pause'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M7.5 2.75V9.25C7.5 9.48233 7.5 9.59849 7.51921 9.69509C7.59812 10.0918 7.908 10.4021 8.30469 10.481C8.40129 10.5002 8.51745 10.5002 8.74978 10.5002C8.9821 10.5002 9.09871 10.5002 9.19531 10.481C9.592 10.4021 9.90205 10.0918 9.98096 9.69509C10 9.59934 10 9.48437 10 9.25612V2.74388C10 2.51562 10 2.40043 9.98096 2.30469C9.90205 1.908 9.59178 1.59812 9.19509 1.51921C9.09849 1.5 8.98233 1.5 8.75 1.5C8.51767 1.5 8.40129 1.5 8.30469 1.51921C7.908 1.59812 7.59812 1.908 7.51921 2.30469C7.5 2.40129 7.5 2.51767 7.5 2.75Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
            <path
                d='M2 2.75V9.25C2 9.48233 2 9.59849 2.01921 9.69509C2.09812 10.0918 2.408 10.4021 2.80469 10.481C2.90129 10.5002 3.01745 10.5002 3.24978 10.5002C3.4821 10.5002 3.59871 10.5002 3.69531 10.481C4.092 10.4021 4.40205 10.0918 4.48096 9.69509C4.5 9.59934 4.5 9.48437 4.5 9.25612V2.74388C4.5 2.51562 4.5 2.40043 4.48096 2.30469C4.40205 1.908 4.09178 1.59812 3.69509 1.51921C3.59849 1.5 3.48233 1.5 3.25 1.5C3.01767 1.5 2.90129 1.5 2.80469 1.51921C2.408 1.59812 2.09812 1.908 2.01921 2.30469C2 2.40129 2 2.51767 2 2.75Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
