// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconTrashFull = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Trash Full'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M7 5V8.5M5 5V8.5M3 3V8.9C3 9.46005 3 9.73988 3.10899 9.9538C3.20487 10.142 3.35774 10.2952 3.5459 10.3911C3.7596 10.5 4.0395 10.5 4.59845 10.5H7.40155C7.9605 10.5 8.23999 10.5 8.4537 10.3911C8.64186 10.2952 8.79524 10.142 8.89111 9.9538C9 9.74009 9 9.4605 9 8.90155V3M3 3H4M3 3H2M4 3H8M4 3C4 2.53406 4 2.3012 4.07612 2.11743C4.17761 1.8724 4.37216 1.67761 4.61719 1.57612C4.80096 1.5 5.03406 1.5 5.5 1.5H6.5C6.96594 1.5 7.19891 1.5 7.38268 1.57612C7.62771 1.67761 7.82233 1.8724 7.92383 2.11743C7.99995 2.3012 8 2.53406 8 3M8 3H9M9 3H10'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
