// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconSlider01 = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Slider01'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M7 7.5H10.5M1.5 7.5H2.5M2.5 7.5C2.5 8.19036 3.05964 8.75 3.75 8.75C4.44036 8.75 5 8.19036 5 7.5C5 6.80964 4.44036 6.25 3.75 6.25C3.05964 6.25 2.5 6.80964 2.5 7.5ZM10 4.5H10.5M1.5 4.5H5M8.25 5.75C7.55964 5.75 7 5.19036 7 4.5C7 3.80964 7.55964 3.25 8.25 3.25C8.94036 3.25 9.5 3.80964 9.5 4.5C9.5 5.19036 8.94036 5.75 8.25 5.75Z'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
