// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconChartBarVertical01 = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Chart Bar Vertical01'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M4.5 5.5V10M4.5 5.5H2.2998C2.01978 5.5 1.87991 5.5 1.77295 5.5545C1.67887 5.60243 1.60243 5.67887 1.5545 5.77295C1.5 5.8799 1.5 6.02002 1.5 6.30005V10H4.5M4.5 5.5V2.80005C4.5 2.52002 4.5 2.37991 4.5545 2.27295C4.60243 2.17887 4.67887 2.10243 4.77295 2.0545C4.8799 2 5.01978 2 5.2998 2H6.6998C6.97983 2 7.12014 2 7.22709 2.0545C7.32117 2.10243 7.39738 2.17887 7.44531 2.27295C7.49981 2.37991 7.5 2.52002 7.5 2.80005V4M4.5 10H7.5M7.5 10L10.5 10V4.80005C10.5 4.52002 10.4998 4.3799 10.4453 4.27295C10.3974 4.17887 10.3215 4.10243 10.2274 4.0545C10.1204 4 9.98003 4 9.7 4H7.5M7.5 10V4'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
