// This file was generated by [svg-to-component](https://github.com/mesalilac/svg-to-component)

/** biome-ignore-all assist/source/useSortedAttributes: Auto generated */

import type { JSX } from 'solid-js';

export const IconFolder = (props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
    return (
        <svg
            role='img'
            aria-label='Folder'
            width='12'
            height='12'
            viewBox='0 0 12 12'
            fill='none'
            {...props}
        >
            <path
                d='M1.5 3V8.4C1.5 8.96005 1.5 9.23988 1.60899 9.4538C1.70487 9.64196 1.85774 9.79524 2.0459 9.89111C2.2596 10 2.5395 10 3.09845 10H8.90154C9.4605 10 9.73999 10 9.9537 9.89111C10.1419 9.79524 10.2952 9.64205 10.3911 9.45389C10.5001 9.23998 10.5001 8.95995 10.5001 8.3999L10.5001 4.59989C10.5001 4.03984 10.5001 3.75981 10.3911 3.5459C10.2952 3.35774 10.142 3.20487 9.95379 3.10899C9.73988 3 9.46005 3 8.9 3H6M1.5 3H6M1.5 3C1.5 2.44772 1.94772 2 2.5 2H4.33726C4.58185 2 4.70443 2 4.81952 2.02763C4.92156 2.05213 5.01893 2.09263 5.1084 2.14746C5.20928 2.20928 5.29591 2.29591 5.46875 2.46875L6 3'
                stroke='currentColor'
                stroke-linecap='round'
                stroke-linejoin='round'
            />
        </svg>
    );
};
