
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getVisualNovelById(id: string) : Promise<Result<VisualNovel, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_visual_novel_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Setting, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTagsWithVisualNovels() : Promise<Result<TagWithVisualNovels[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tags_with_visual_novels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTags() : Promise<Result<Tag[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeTags() : Promise<Result<Tag[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeVisualNovelById(id: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_visual_novel_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSettings(payload: UpdateSettingsRequest) : Promise<Result<Setting, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async utilScanLibrary() : Promise<Result<VisualNovel[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("util_scan_library") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async utilLaunchVisualNovel(id: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("util_launch_visual_novel", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async utilSyncLibrary() : Promise<Result<VisualNovel[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("util_sync_library") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVisualNovels() : Promise<Result<VisualNovel[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_visual_novels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async removeTagFromVisualNovelById(visualNovelId: string, tagId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_tag_from_visual_novel_by_id", { visualNovelId, tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeTagById(id: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_tag_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createVisualNovel(payload: CreateVisualNovelRequest) : Promise<Result<VisualNovel, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_visual_novel", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStats() : Promise<Result<GeneralStats, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeAllVisualNovels() : Promise<Result<VisualNovel[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_all_visual_novels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateVisualNovel(payload: UpdateVisualNovelRequest) : Promise<Result<VisualNovel, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_visual_novel", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async utilCloseVisualNovel(id: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("util_close_visual_novel", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTag(payload: UpdateTagRequest) : Promise<Result<Tag, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tag", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTag(payload: CreateTagRequest) : Promise<Result<Tag, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_tag", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CommandError = { kind: "Database"; message: string } | { kind: "NotFound" } | { kind: "Io"; message: string } | { kind: "LaunchFailure"; message: string } | { kind: "AlreadyRunning" } | { kind: "Unknown"; message: string }
export type CreateTagRequest = { name: string }
export type CreateVisualNovelRequest = { title: string; description: string | null; coverPath: string | null; playtime: number; dirPath: string; status: VisualNovelStatus | null; executablePath: string; launchOptions: string | null; tags: Tag[] }
export type GeneralStats = { lastPlayedAt: Timestamp | null; totalPlaytime: number; visualNovelCount: number; tagCount: number; unplayedCount: number; playingCount: number; finishedCount: number; backlogCount: number; droppedCount: number }
export type Setting = { id: number; libraryPath: string | null; localeEmulatorExecutablePath: string | null; localeEmulatorLaunchOptions: string | null }
export type Tag = { id: string; name: string; createdAt: Timestamp }
export type TagWithVisualNovels = ({ id: string; name: string; createdAt: Timestamp }) & { visualNovels: VisualNovel[] }
export type Timestamp = number
export type UpdateSettingsRequest = { libraryPath: string | null; localeEmulatorExecutablePath: string | null; localeEmulatorLaunchOptions: string | null }
export type UpdateTagRequest = { id: string; name: string }
export type UpdateVisualNovelRequest = { id: string; title: string | null; description: string | null; coverPath: string | null; playtime: number | null; status: VisualNovelStatus | null; executablePath: string | null; launchOptions: string | null; tagIds: string[] }
export type VisualNovel = { id: string; title: string; description: string | null; coverPath: string | null; playtime: number; lastTimePlayedAt: Timestamp | null; status: VisualNovelStatus; dirPath: string; executablePath: string; launchOptions: string | null; isMissing: boolean; createdAt: Timestamp; tags: Tag[] }
export type VisualNovelStatus = "Backlog" | "Playing" | "Finished" | "Dropped"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
